clever_cloud:
    host: "brydggsibxis1tgcxqdg-mysql.services.clever-cloud.com"
    port: "3306"
    username: "umoqspxowm8r0tci"
    password: "![AeegakHxybZW8pRIKCV2qaFDJZit1CebhTHRbXIeeXQ=]"
    db_name: "brydggsibxis1tgcxqdg"
    