  [
  {
  "name": "milk",
  "quantity": 1,
  "category": "DIARY",
  "storage_space": "FRIDGE",
  "expire_by": "2023-07-17"
  },
  {
  "name": "apple",
  "quantity": 3,
  "category": "FRUIT",
  "storage_space": "OTHER",
  "expire_by": "2023-07-22"
  }
  ]